### ISSUE TITLE
Cannot deploy subnet in Local Network

### ISSUE THREAD

**Issue by DeeKay02** [ava-labs/subnet-evm#1038] opened 2024-01-02 20:37 UTC
**Describe the bug**
Unable to deploy subnet in Local Network. Been getting this "node stopped unexpectedly" for weeks.

**To Reproduce**
Just create a subnet and deploy in local network using Avalanche CLI

**Expected behavior**
Subnet be deployed and run smoothly.

**Screenshots**
![image](https://github.com/ava-labs/subnet-evm/assets/48171972/96e8e9ca-f72a-455f-9aa3-a6d71d61fda9)

**Operating System**
WSL

**Comment by ceyonur** [comment] 2024-01-03 11:26
Is this duplicate of #1036?

**Comment by ceyonur** [comment] 2024-05-05 10:15
Closing the stale issue. Feel free to reopen if the problem continues.

**Closed** 2024-05-05 10:15 UTC
Labels: bug
