### ISSUE TITLE
Gnosis Multisig transactions fail when interacting with Precompiles

### ISSUE THREAD

**Issue by friskyfoxdk** [ava-labs/subnet-evm#487] opened 2023-02-03 23:01 UTC
**Describe the bug**
We’re trying to set fee config in the FeeConfig Precompile via a Multisig wallet. It always fails for some unknown reason, but it works when using the newer version of Gnosis Safe.

Other precompiles and other methods seem to have the same issue. We've tried increasing the gas to no avail.

Tested on Version 1.6.0

**To Reproduce**
1. Create a Gnosis Multisig Wallet.
2. Grant access to the wallet to perform an action on the Precompile.
3. Try to submit a transaction for the precompile from the multisig wallet.
4. The transaction should 'succeed', but it won't be marked as 'Executed', nor will it have made the changes you were wanting to make to the precompile.

**Expected behavior**
Expected that the transaction would succeed and execute.

**Logs**
Here is a transaction that 'succeeded' but failed to actually execute in the Multisig.
https://avascan.info/blockchain/dfk/tx/0x738e07e277e8c854e8c4734e22b3a92f28a0f09fce43509d662e0d18135541a2

Avalanche Bug Bounty program can be found [here](https://hackenproof.com/avalanche/avalanche-protocol).

**Comment by aaronbuchwald** [comment] 2023-02-03 23:41
Could you link to the version of the gnosis safe wallet that fails and the version that it succeeds with?

**Comment by friskyfoxdk** [comment] 2023-02-04 16:51
It succeeds with the newer Gnosis Safe architecture, but fails with the older Gnosis Multisig contracts. Here is one we have running on IPFS: https://kingdom-studios.infura-ipfs.io/ipfs/QmfRD4GuqZobNi2NT2C77a3UTQ452ffwstr4fjEJixUgjf/#/wallets

**Comment by friskyfoxdk** [comment] 2023-02-04 16:51
As a mitigation, we are looking into setting up a newer Gnosis Safe implementation for DFK Chain, but it would be preferable if we could use Multisig wallets too. Not sure why they would fail where the others succeed though.

**Comment by aaronbuchwald** [comment] 2023-02-05 00:29
Could you please provide a link to the Gnosis Safe GitHub and the tag or git commit that you deployed that is seeing this failure?

Given that this is fixed in a later version of Gnosis Safe, I'm guessing that a previous version may have used `delegatecall`, which could result in `tx.origin` being the `caller` passed in to the precompile.

You can see the precompile implementation here, which uses `caller` / `msg.sender` rather than `tx.origin`: https://github.com/ava-labs/subnet-evm/blob/master/precompile/fee_config_manager.go#L333.

**Comment by friskyfoxdk** [comment] 2023-02-05 06:20
@aaronbuchwald , here is the repo, using the latest version 1.6.0: https://github.com/gnosis/MultiSigWallet

The weird thing is whenever we use these wallets to execute other methods on other contracts (we use these for most of our management) it always shows the msg.sender as the safe contract, as designed, regardless of which of the signers executed it.

So my guess is there must be something causing the precompiles to have something other than the msg.sender being set in the `caller` variable. It may be that the tx.origin is being passed in instead. 

The tx.origin in this example would be one of the executors, who are NOT holding the admin role for the precompile, but the msg.sender should be the safe wallet, which DOES hold the admin role.

**Comment by friskyfoxdk** [comment] 2023-02-05 06:22
I wonder if it would result in the same issue if a smart contract were to be created to interact with a precompile. Incidentally, we are considering this architecture for allowing people to automatically become whitelisted by a smart contract on our chain. In this instance, we would give the smart contract the admin role for the deploy allowlist precompile, and when people submitted a transaction to the smart contract, it would whitelist them. In that situation, a similar setup would occur where the tx.origin wouldn't have access but the msg.sender would.

**Comment by ceyonur** [comment] 2023-02-06 10:36
@friskyfoxdk 

I think the root cause is the supplied gas in the gnosis-safe/precompile. I added some logs on my local network and saw this error in my logs:
```
WARN [02-06|13:16:40.356] <w9qCXUkCRWYcFWEAmbCWYDPe5ToRddBSUM3gXbq8A13S8n5kx Chain> github.com/ava-labs/subnet-evm/core/vm/contracts_stateful.go:32: hop ret= err="out of gas"
```
After that I increased the supplied gas in Metamask while calling the contract with 
```
submitTransaction("0x0200000000000000000000000000000000000003", "0", "0x8f10b5860000000000000000000000000000000000000000000000000000000001406f400000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000003b9aca000000000000000000000000000000000000000000000000000000000005f5e100000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000989680000000000000000000000000000000000000000000000000000000000007a120"
```
I added `180.000` (SetFeeConfig gas cost) more gas to what’s suggested via Metamask (suggested: 351210, I gave total of 531210) . Then it changed the fee config. 
Note: don’t use the function above directly as it contains my own janky fee configs :smile: 
cc: @aaronbuchwald

**Comment by friskyfoxdk** [comment] 2023-02-06 20:00
Thanks @ceyonur for investigating. Unfortunately increasing the gas even by two orders of magnitude didn't help in our case. I'm not sure what else to try at this point, but we'll keep poking at it.

**Comment by aaronbuchwald** [comment] 2023-02-07 20:40
Looks like this issue comes from padding added to the call by the Safe Contract:

```
WARN [02-07|06:15:34.601] <q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi Chain> github.com/ava-labs/subnet-evm/precompile/fee_config_manager.go:320: setFeeConfig errorred outOfGas=suppliedGas LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
INFO [02-07|06:15:46.550] <q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi Chain> github.com/ava-labs/subnet-evm/core/vm/evm.go:231: Call operation on FeeConfigManager caller=0xFe699Ef422c0977FD6F70aC3203C4Ff05CAac060 addr=0x0200000000000000000000000000000000000003 input="[143 16 181 134 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 125 120 64 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 42 5 242 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 120 104 192 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 84 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 27 193 109 103 78 200 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 13 224 182 179 167 100 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]" gas=19,591,856 value=0
WARN [02-07|06:15:46.556] <q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi Chain> github.com/ava-labs/subnet-evm/precompile/fee_config_manager.go:331: setFeeConfig errorred failed to unpack fee config input="invalid input length for fee config input: 284" input=00000000000000000000000000000000000000000000000000000000017d78400000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000012a05f20000000000000000000000000000000000000000000000000000000000047868c0000000000000000000000000000000000000000000000000000000000000005400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001bc16d674ec800000000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000000000000000
INFO [02-07|06:16:32.977] <q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi Chain> github.com/ava-labs/subnet-evm/internal/ethapi/api.go:1819: Submitted transaction hash=0x42c40f607bd329c3a8efb68a9db6108a28ee5dd9642ae34384d85890559485e0 from=0x124D13414b8bbeFd6e03B0acfA1d1f709E8A35A3 nonce=452 recipient=0xFe699Ef422c0977FD6F70aC3203C4Ff05CAac060 value=0 type=2 gasFeeCap=20,000,000,000 gasTipCap=20,000,000,000 gasPrice=20,000,000,000
INFO [02-07|06:16:36.464] <q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi Chain> github.com/ava-labs/subnet-evm/core/vm/evm.go:231: Call operation on FeeConfigManager caller=0xFe699Ef422c0977FD6F70aC3203C4Ff05CAac060 addr=0x0200000000000000000000000000000000000003 input="[143 16 181 134 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 125 120 64 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 42 5 242 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 120 104 192 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 84 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 27 193 109 103 78 200 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 13 224 182 179 167 100 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]" gas=19,591,856 value=0
WARN [02-07|06:16:36.464] <q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi Chain> github.com/ava-labs/subnet-evm/precompile/fee_config_manager.go:331: setFeeConfig errorred failed to unpack fee config input="invalid input length for fee config input: 284" input=00000000000000000000000000000000000000000000000000000000017d78400000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000012a05f20000000000000000000000000000000000000000000000000000000000047868c0000000000000000000000000000000000000000000000000000000000000005400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001bc16d674ec800000000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000000000000000
```

The precompile currently strictly enforces the length matches the required length, but this is a discrepancy between the behavior of the precompile and other smart contracts, which may allow padding.

We should consider changing this in a network upgrade of subnet-evm alongside the proposed changes to allow a manager role and emit events from precompiles: https://github.com/ava-labs/subnet-evm/issues/345.

**Comment by friskyfoxdk** [comment] 2023-02-10 19:33
Thanks @aaronbuchwald , I think that would be great :)

**Closed** 2023-12-15 18:18 UTC
Labels: bug
