### ISSUE TITLE
subnet merkle tree verify failure

### ISSUE THREAD

**Issue by elmtlab** [ava-labs/subnet-evm#278] opened 2022-09-26 14:21 UTC
o Reproduce
I just follow the instruction of https://docs.avax.network/subnets/setup-dfk-node

Expected behavior

Screenshots
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/23255413/192300550-cf8302c3-e80a-410c-bc01-8351ca3f4192.png">

Logs
[09-22|16:17:48.354] ERROR bootstrap/block_job.go:88 block failed verification during bootstrapping {"blkID": "2suDwNrHE8AMVRYZuoZYotWVYV9XcKehCfEnURSfEF5VHTvgr1", "error": "rpc error: code = Unknown desc = invalid merkle root (remote: a4813b055e6dc3adc8b3ce1a61402a5bbdefedf23b5ee7b53fa9754a44123c88 local: b2137934960f6665e360c19cca933fba971dd9dbcbb4201651091a11344ae4b8)"}
[09-22|16:17:48.355] FATAL handler/handler.go:283 shutting down chain {"reason": "received an unexpected error", "error": "failed to execute job 2suDwNrHE8AMVRYZuoZYotWVYV9XcKehCfEnURSfEF5VHTvgr1 due to failed to verify block in bootstrapping: rpc error: code = Unknown desc = invalid merkle root (remote: a4813b055e6dc3adc8b3ce1a61402a5bbdefedf23b5ee7b53fa9754a44123c88 local: b2137934960f6665e360c19cca933fba971dd9dbcbb4201651091a11344ae4b8) while processing sync message: (Op: ancestors, NodeID: NodeID-H94Q5zdkBByZVWvqrB5ByiX4dZdG1J45y, RequestID: 18, NumContainers: 63)"}

[error_log.txt](https://github.com/ava-labs/subnet-evm/files/9647028/error_log.txt)

Operating System
MAC os M1 chip

**Comment by ceyonur** [comment] 2022-09-26 14:45
Answered on https://github.com/ava-labs/avalanchego/issues/1147
> They recently upgraded their network with network upgrades in subnet-evm. Check their [upgrade.json ](https://github.com/ava-labs/subnet-evm/blob/master/networks/mainnet/53935/upgrade.json)file and put that into the chain configuration under `$HOME/.avalanchego/configs/chains/q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi` I assumed you use `$HOME/.avalanchego` as the main directory, if you use anything else use the same pattern for your own directory.
> 
> See more info on https://docs.avax.network/subnets/subnet-upgrade#changing-subnet-configuration

**Comment by aaronbuchwald** [comment] 2022-10-05 17:32
Closing since this seems to have been answered and was caused by not including the upgrade bytes for DFK correctly.

**Closed by aaronbuchwald** 2022-10-05 17:32 UTC
Labels: bug
